name: TopIsland
main: BeeAZ\TopIsland\Main
version: 1.0.0
api: 4.0.0
author: BeeAZ-pm-pl

commands:
  topisland:
    description: Top Island Command
    aliases: ["topis"]
    permission: topisland.command
permissions:
  topisland.command:
   default: true
